version: "3.9"
    
services:

  wordpress:
    container_name: devops7 
    image: devops7
    ports:
      - 220:222
      - 8888:80    

    volumes:
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh

    networks:
      - proxy

volumes:
  devops7_db: {}

networks:
  proxy:
    name: proxy

